# Generated by Django 5.1.3 on 2024-11-17 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="adress",
            new_name="address",
        ),
    ]
